comp = ["Motherboard", "CPU", "RAM", "Case", "M.2", "GPU", "Fans"]
print(sorted(comp))
print(sorted(comp, reverse = True))
comp.reverse()
print(comp)
comp.reverse()
comp.sort()
print(comp)
comp.sort(reverse = True)
print(comp)
print(f"This Computer has {len(comp)} parts.")
comp.sorted()
print(comp)